### ISSUE TITLE
Transactions missing

### ISSUE THREAD

**Issue by KoenWijnstok** [BunqCommunity/BunqDesktop#103]
I have just installed BunqDesktop and I notice a lot of missing transactions.
Most of the recent transactions (as in <3 weeks) are correct, but when I go back in time there are more and more transactions missing. I do see them in the normal bunq app by the way.

It gets worse that when I go a couple of months back in time there are hardly any transactions left.
I have attached 2 screenshots, one from my phone and the other one from BunqDesktop.
In both screenshots are the transactions listed from December 1st. Desktop contains 1 transaction while I have had 8 transactions in reality.

On the screenshot of BunqDesktop you see the top transaction from de Efteling. In the bunq app there are 10 transactions between de Efteling and the Jumbo.

![desktop](https://user-images.githubusercontent.com/3371628/34740104-9ecb01dc-f57e-11e7-87ca-4ea1badf3c7d.PNG)
![screenshot_20180109-204455](https://user-images.githubusercontent.com/3371628/34740105-9ee5c36e-f57e-11e7-95fa-649de280f16b.png)

**Comment by imme-emosol** [comment]
Could it be something with the results of the api itself (instead of something with the app)?

**Comment by KoenWijnstok** [comment]
I have checked 2 different installations of BunqDesktop and both have this.
These also have 2 different API keys.

What I find strange is that it's not just 1 type of payment which is
missing.
It's a card payment, direct debit, bunq "invoice of €0" and some regular
scheduled payments.
Only the card payment is shown.

**Comment by Crecket** [comment]
Currently the app fetches 50 items from the different endpoints. So 50 bunq.me request, 50 credit card payments and so on. But because you tend to do more payments you might see a really old request from months ago, whereas the payments only go back a few weeks.

I'll make sure to prioritize the issue for pagination because I just realized how confusing this behavior is for users. Thanks for taking to time to report the bug so thoroughly btw!

You can track the progress on that issue here: #3
