### ISSUE TITLE
Create a new session when an unauthorized error is shown

### ISSUE THREAD

**Issue by Crecket** [bunqCommunity/bunqDesktop#117]
If one of the endpoints returns an error which signals that the session is invalid or expired it should automatically create a new one

**Comment by OGKevin** [comment]
Hmm, wouldn't it be better to store the session expiration date and make a call in the last 30 sec so that the bunq backend auto renews it 😉. In the `session-server` response there will be the user object and in there there should be a time out field containing how long a session will last in seconds.

This way you only use one bunq-session per actual user-session (when logs in to bunqDesktop) and just make a call to `/user` or in the last 30 seconds of the bunq-session to extend it another x seconds found in the session-server response.

**Comment by Crecket** [comment]
Since the new system prevents most cases where this error might occur I'm closing this issue. Also, the API's error doesn't provide context for why the request was unauthorized and trying to fix it by sending new session-server requests for example might get the IP address blocked for a certain duration
