### ISSUE TITLE
Use Connect budget as account balance 

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#217]
Now the balance of a Connect is € 0,00. In the bunq app the balance is the same as the Connect budget.

**Comment by Cheaternl** [comment]
Can you describe what you mean with this? Just out of interest of me.

**Comment by Crecket** [comment]
@Cheaternl when you have access to a Connect account and the person who shared it with you set a budget, the budget is used as the balance that you see in the app. 

Right now in BunqDesktop you'll just see a balance of 0.00 in all situations. So this issue is to display the budget amount as the balance amount
