### ISSUE TITLE
Missing linux-build from latest release and hashes

### ISSUE THREAD

**Issue by L00Cyph3r** [BunqCommunity/bunqDesktop#256]
The latest release (0.8.11) does not contain a 'linux-unpacked.tar.gz' file or anything similiar.
Since I'm currently trying to maintain the Arch AUR package it would be nice if we could make sure this file exists in coming updates in an expectable filename.

And if it's not too much of a hassle, it might be nice if the build-process creates SHA-hashes for the generated distributables (since it's somewhat bank/privacy-related). Of course I could generate hashes myself, but 'original' ones are probably trustworthier.

**Comment by Crecket** [comment]
I'll check why the unpacked file is suddenly no longer uploaded since 0.8.11, it might have to do with the hotfix I ran a while.

For the hashes you can always check the build for that specific release. At the bottom of every travis build a list of hashes are created. I'll reply here for the correct ones for the current build when I fix it 👍

**Comment by Crecket** [comment]
Added the download file and the checksum for it is `8f36b98ea79b1323ffe3968c2105a099073700c536ed005868f6c702de5cb68c`. I'll make a habit out of adding a link to the travis build as well so you can find the hashes more easily next time and to keep things a bit more transparent.

Thanks for reporting this btw, I completely missed it 👍
