### ISSUE TITLE
Display transfers between accounts differently like in the bunq app

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#293]
I'm using Nightly build 2018-08-28 23:06:03 on windows. 

As mentioned in [issue 292](https://github.com/BunqCommunity/bunqDesktop/issues/292) the events are not tied to the correct accounts. For instance in the below screenshot there are strange account names used and the icons are swapped for the first two events. This was a transfer from "Automatische betalingen" to "creditcard".
![bunqdesktop-wrong-info](https://user-images.githubusercontent.com/23123995/44770132-4d337800-ab67-11e8-91f2-2e71760e62db.png)
 
This is how it looks on my phone when I select the "Automatische betalingen account":
![screenshot_20180829-072513](https://user-images.githubusercontent.com/23123995/44770153-60dede80-ab67-11e8-8109-659b4de48919.jpg)

**Comment by Crecket** [comment]
The icon and name are correct. The display name for an outgoing payment vs incoming payment are formatted differently by bunq. And the icon is showing the image of the counterparty.

So the outgoing payment is showing the targeted account's profile picture and the other way around.

I changed the title so I'll display these payments like it is done in the bunq app. Where it simply shows the account names instead of using the counter_party name

**Comment by Crecket** [comment]
That is how bunq formats the names between your own alias and counterparty aliases. Even if the counterparty is one of your own accounts

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/44783190-dc518780-ab89-11e8-96b7-3109b0ab9290.png)

**Comment by JeroenEeuwes** [comment]
This was solved earlier, but with the Nightly build 2018-08-29 23:06:14 the strange names are back again. So it shows Jeroen Eeuwes CJ instead of "automatische betalingen":
![bunqdesktop - request info](https://user-images.githubusercontent.com/23123995/44831355-77983a80-ac26-11e8-96fe-d9ef9f24d147.png)
