### ISSUE TITLE
When no specific event icon is present it is shown as a blank person profile

### ISSUE THREAD

**Issue by JeroenEeuwes** [bunqCommunity/bunqDesktop#296]
I'm using Nightly build 2018-08-28 23:06:03 on windows.

In the event overview there can be specific logo's attached to events. For example the yellow/white logo of Jumbo. 
When there isn't a specific event icon the bunq App still uses different pictures on different events. In bunqDesktop this is shown as blank person profile. 
![blank-person-profile](https://user-images.githubusercontent.com/23123995/44770899-c207b180-ab69-11e8-8a4e-187e32c9c457.png)
![screenshot_20180829-082934-icons](https://user-images.githubusercontent.com/23123995/44770905-c502a200-ab69-11e8-9cc1-267c3b73fff5.jpg)

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/45547499-3fe1e300-b821-11e8-8967-67ac54618ea5.png)
I added the default images to certain types like virtual/real card payments and company vs person. 

Because I don't know all the different things that bunq checks for to show these so there might be some inconsistencies
