### ISSUE TITLE
Quit the Mac app using cmd Q

### ISSUE THREAD

**Issue by ntimo** [BunqCommunity/BunqDesktop#8]
Hello,
it would be awesome if it would be possible to quite the Mac app using the cmd Q shortcut like every other Mac app :)

Have a great day,
Timo

**Comment by DennisSnijder** [comment]
@ntimo Thanks for reporting the issue, I will have a look into it shortly!

**Comment by ntimo** [comment]
after the new update. This is still not supported :)

**Comment by DennisSnijder** [comment]
@ntimo correct, the framework we are using (Electron) describes that CMD + Q is not a default functionality within MacOS (Which sounds a bit weird to me).
This means I need to implement it myself, which might take a bit longer since we have higher priorities at the moment.

I will keep you updated 🙂

**Comment by DennisSnijder** [comment]
@ntimo the functionality has been implemented! upon the next release it will be available for download! 😊
